disabled_rules:
  - trailing_whitespace
  - todo
  - line_length
  - function_body_length
  - type_body_length
  - nesting
  - identifier_name
  - trailing_comma
  - vertical_whitespace
  - implicit_optional_initialization
  - comma
  - cyclomatic_complexity
  - force_cast
  - file_length
  - force_unwrapping
  - redundant_discardable_let
  - trailing_newline
opt_in_rules: []
included:
  - Sources
