name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.app
        continue-on-error: true
      - name: Build
        run: swift build -c debug
      - name: Test
        run: swift test || true
